Update changelog since v5.1.0
purescript/purescript-tuples pull request #45
Opened 2021-01-20 05:11 UTC by thomashoneyman

**Description of the change**

This PR updates the CHANGELOG in preparation for the upcoming release of this library.

Related: purescript/purescript#3985

2021-01-20 12:11 UTC, JordanMartinez commented on CHANGELOG.md
> +- Added `foldr1` and `foldl` implementations to `Foldable1 (Tuple a)` instance and removed `foldl1` (#39, #43)
I don't think this is a breaking change.

2021-01-20 12:12 UTC, JordanMartinez commented on CHANGELOG.md
> +- Added `foldr1` and `foldl` implementations to `Foldable1 (Tuple a)` instance and removed `foldl1` (#39, #43)
Move it down to 'Other Improvements' similar to what Miles did in another PR?

2021-01-20 12:13 UTC, JordanMartinez commented on CHANGELOG.md
>  New features:
#40 should appear here, correct? Something like this:
> Added `Generic` instance for `Tuple` (#40)

2021-01-20 12:13 UTC, JordanMartinez requested changes
A few fixes

2021-01-20 18:03 UTC, thomashoneyman commented on CHANGELOG.md
> +- Added `foldr1` and `foldl` implementations to `Foldable1 (Tuple a)` instance and removed `foldl1` (#39, #43)
I wasn't sure where to put this; it's changed because the `Foldable1` class has changed, and if we were to upgrade the dependency and apply this change in the library in normal circumstances it would be breaking. (For example, you could no longer use `fold1` via the class.)

But since it's part of adding support for 0.14, perhaps "other improvements" is the way to go for this particular case.

2021-01-20 18:05 UTC, thomashoneyman commented on CHANGELOG.md
> +- Added `foldr1` and `foldl` implementations to `Foldable1 (Tuple a)` instance and removed `foldl1` (#39, #43)
I've moved it to "other improvements" for the time being.

2021-01-21 01:49 UTC, JordanMartinez approved these changes

2021-01-21 01:49 UTC, merged